steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '${_REPOSITORY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}', '-f', 'gcp/workload-vm/Dockerfile', '.' ]

images:
- '${_REPOSITORY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}'
